---
- name: Install Docker and configure user
  hosts: private
  become: true
  tasks:
    - name: Update the package list
      apt:
        update_cache: yes

- name: Copy SSH key to private instances via bastion
  hosts: private
  gather_facts: False
  become: yes

- name: Copy SSH key to private instances via bastion
  hosts: private
  gather_facts: False
  become: yes

  tasks:
    - name: Copy SSH key to private instance
      shell: >
        echo "$ANSIBLE_SSH_PRIVATE_KEY" > /tmp/private_key.pem &&
        ssh-copy-id
        -i /tmp/private_key.pem
        -o ProxyCommand="ssh -W %h:%p -q -i /tmp/private_key.pem {{ hostvars['bastion']['ansible_host'] }}"
        {{ inventory_hostname }}
      args:
        executable: /bin/bash



    - name: Install Docker
      apt:
        name: docker.io
        state: present
      become: true

    - name: Add the ubuntu user to the docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Output confirmation messages
      debug:
        msg: "Server setup completed!"

    - name: Output Docker version
      command: "docker --version"

- name: Pull Docker image from Docker Hub
  hosts: private
  become: true
  tasks:
    - name: Pull Docker image from Docker Hub
      command: "docker pull your_docker_image"
