name: Deploy to EC2 Docker Hosts

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package

    - name: Archive Artifact
      uses: actions/upload-artifact@v2
      with:
        name: java-artifact
        path: target/*.jar
    
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/cloudhight:latest

    # - name: Build and Push Docker Image
    #   env:
    #     DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
    #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    #   run: |
    #     docker build -t $DOCKER_REGISTRY/cloudhight:latest .
    #     docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
    #     docker push $DOCKER_REGISTRY/cloudhight:latest

    - name: Deploy to EC2 Instances
      env:
        ANSIBLE_PLAYBOOK_PATH: playbook.yml
        INVENTORY_PATH: inventory.ini
        ANSIBLE_SSH_PRIVATE_KEY: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
      run: |
        ansible-playbook -i $INVENTORY_PATH $ANSIBLE_PLAYBOOK_PATH --private-key=$ANSIBLE_SSH_PRIVATE_KEY
